    <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.DB.Acl" Version="28.0.2--ci.1" />
    <PackageReference Include="CK.DB.Zone" Version="28.0.2--ci.1" />
    <PackageReference Include="CK.DB.Group.SimpleNaming" Version="28.0.2--ci.1" />
    <!-- By default, groups are uniquely named.
         Adding CK.DB.Zone.SimpleNaming makes Group names relative to their Zone. -->
    <PackageReference Include="CK.DB.Zone.SimpleNaming" Version="28.0.2--ci.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.IO.Workspace\CK.IO.Workspace.csproj" />
    <ProjectReference Include="..\CK.IO.UserProfile.Workspace\CK.IO.UserProfile.Workspace.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="**\*.sql;**\*.tql" />
  </ItemGroup>
</Project>